### ISSUE TITLE
Issue with baselineSGP

### ISSUE THREAD

**Issue by susd-casey** [CenterForAssessment/SGP#1087]
I am having an issue running any kind of data through. State is Arizona and data is recent 2015 & 2016 formatted identical to DEMO data except where year and content area differ but I have matched them to what SGPState is looking for.
Error is:
Error in strsplit(names, "_") : non-character argument

I have tried expanded long format as seen in the demo data, as well as compressed based on minimum requirements discussed on the wiki.
I have attached the log.
[SGP-1.7.0.0_2017-05-17.txt](https://github.com/CenterForAssessment/SGP/files/1008371/SGP-1.7.0.0_2017-05-17.txt)

**Comment by dbetebenner** [comment]
Could you post the R script you were running?

**Comment by susd-casey** [comment]
## Load library
install.packages("SGP")
library(SGP)

## Read in file
scottsdale <- read.csv("sgp_scottsdale.csv")

## Reformat types & headings
str(scottsdale)
colnames(scottsdale)[1] <- "ID"
scottsdale$ID <- as.character(scottsdale$ID)
colnames(scottsdale)[2] <- "CONTENT_AREA"
scottsdale$CONTENT_AREA <- as.character(scottsdale$CONTENT_AREA)
colnames(scottsdale)[3] <- "YEAR"
scottsdale$YEAR <- as.character(scottsdale$YEAR)
colnames(scottsdale)[4] <- "GRADE"
scottsdale$GRADE <- as.character(scottsdale$GRADE)
colnames(scottsdale)[5] <- "SCALE_SCORE"
scottsdale$SCALE_SCORE <- as.numeric(scottsdale$SCALE_SCORE)
colnames(scottsdale)[6] <- "VALID_CASE"
scottsdale$VALID_CASE <- as.character(scottsdale$VALID_CASE)

#Begin analysis
output <- abcSGP(sgp_object = scottsdale, state = "AZ")

**Comment by dbetebenner** [comment]
See my response above. I believe you just need to turn off the baseline SGP analyses.

**Comment by susd-casey** [comment]
Yes that fixed it. Thank you!

**Comment by dbetebenner** [comment]
😄
