### ISSUE TITLE
TOC Getting Started File Out of Date

### ISSUE THREAD

**Issue by vinceparedes** [CenterForAssessment/SGP#1252]
Just a little thing as I am refreshing my memory with SGP. In the Getting Started file the Table of Contents (right nav) from Data Analysis down are anchor tags that don't resolve. That content is now in separate files. 

Filename is:
/SGP-8906c2a/docs/articles/SGP.html

**Comment by dbetebenner** [comment]
I'm assuming you mean:

https://sgp.io/articles/SGP.html#data-analysis


Thanks. Embarrassingly, those tags still don't have any content associated with them.

**Comment by vinceparedes** [comment]
Yes that is the one I mean. The separate files I saw were on other subjects not the TOC subjects. 

I might have some time to create some of the content for you. If I can clear some current stuff. Or, you might prefer to do it yourself to make sure it is right on the first pass. 

Vince.
