### ISSUE TITLE
There's a test plot at the bottom of your vignette

### ISSUE THREAD

**Issue by davemoyer** [CenterForAssessment/SGP#1264]
It looks like you were testing out plotly, and left the test viz at the bottom of the Data Prep vignette. It's likely not bothering anyone, but I suspect you don't want it there.

https://sgp.io/articles/SGP_Data_Preparation.html:

```
# Plotly test

{r echo=FALSE, warning=FALSE, message=FALSE}
library(plotly)
p <- plot_ly(economics, x = ~date, y = ~unemploy / pop)
p
```

**Comment by dbetebenner** [comment]
Hey Dave,

Yeah. Wanted to figure out to embed plotly graphs in the vignettes so we could eventually embed more relevant plots (that we never got around to). We did talk about making another big push on documentation in the coming months. So stay tuned!

**Comment by davemoyer** [comment]
No biggie - just wanted to contribute.

Cheers,
D
