### ISSUE TITLE
Error message: There are both positive and negative numbers in j (Chinese: j 中同时存在正数和负)

### ISSUE THREAD

**Issue by RuoCJ** [CenterForAssessment/SGP#1450]
When I used SGP to calculate the student's percentage growth rating, I encountered the following error message: 
```
There are both positive and negative numbers in j
(Chinese: j 中同时存在正数和负)
```

My R version: 4.4.1
My R code:
```
library(SGP)
library(readxl)
library(openxlsx)

data <- read_excel("D:/twice_data_rank_school.xlsx")

SGP_Data <- data
names(SGP_Data) <- c("id", "score_202301", "rank_202301", "score_202306", "rank_202306")

SGP_Data$score_202301 <- as.numeric(SGP_Data$score_202301)
SGP_Data$rank_202301 <- as.numeric(SGP_Data$rank_202301)
SGP_Data$score_202306 <- as.numeric(SGP_Data$score_202306)
SGP_Data$rank_202306 <- as.numeric(SGP_Data$rank_202306)

SGP_Results <- tryCatch({
  studentGrowthPercentiles(
    panel.data = SGP_Data,
    sgp.labels = list(my.year = "2023", my.subject = "TotalScore"),
    percentile.cuts=c(1,35,65,99),
    grade.progression = c(202301, 202306) 
  )
}, error = function(e) e)

if (inherits(SGP_Results, "error")) {
  print(SGP_Results$message)
} else {
  write.xlsx(SGP_Results, "out_twice_data.xlsx", row.names = FALSE)
}
```

My Dataset:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/84036/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/84036/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

id | score_202301 | rank_202301 | score_202306 | rank_202306
-- | -- | -- | -- | --
2 | 681.0 | 1.0 | 674.0 | 3.0
10 | 666.5 | 2.0 | 630.5 | 39.0
12 | 665.0 | 3.0 | 640.0 | 28.0
15 | 664.5 | 4.0 | 647.5 | 14.0
18 | 663.5 | 5.0 | 663.0 | 6.0
30 | 660.0 | 6.0 | 649.5 | 13.0
31 | 660.0 | 6.0 | 654.0 | 11.0
39 | 655.0 | 8.0 | 683.5 | 1.0
43 | 652.5 | 9.0 | 645.0 | 19.0
49 | 649.5 | 10.0 | 647.0 | 15.0
52 | 649.0 | 11.0 | 646.5 | 18.0
53 | 648.5 | 12.0 | 655.0 | 10.0

</body>

</html>

I have the test scores of the same group of students for two exams, and I have calculated the rankings of the students in each exam. I want to use this data to calculate the growth level of each student, but I received the error message mentioned above. How should I modify my code?

**Comment by dbetebenner** [comment]
Hello,

Sorry for the slow reply. You're close, you just need to format your input data correctly.

You don't need the rank variables. You need 

1. And ID
2. Two grade variables
3. Two total score variables

The first few rows of your data should look like


id | grade_202301|grade_202306|score_202301  | score_202306 
-- | -- | -- | -- | --
2 | 202301 | 202306 | 681.0 | 674.0 
10 | 202301 | 202306 | 666.5 | 630.5 
12 | 20230 | 202306 | 665.0 | 640.0 

Also, hopefully you have about a 1,000 cases (rows) of data. You might run into problems (both analytic as well as interpretive) if the number of cases that you have is small.

**Comment by RuoCJ** [comment]
> Hello,
> 
> Sorry for the slow reply. You're close, you just need to format your input data correctly.
> 
> You don't need the rank variables. You need
> 
> 1. And ID
> 2. Two grade variables
> 3. Two total score variables
> 
> The first few rows of your data should look like
> 
> id	grade_202301	grade_202306	score_202301	score_202306
> 2	202301	202306	681.0	674.0
> 10	202301	202306	666.5	630.5
> 12	202301	202306	665.0	640.0
> Also, hopefully you have about a 1,000 cases (rows) of data. You might run into problems (both analytic as well as interpretive) if the number of cases that you have is small.

Thank you very much for your prompt and detailed response.  It has clarified my doubts significantly.  I will proceed with the adjustments as discussed and attempt to reformat the data accordingly.

Should everything work out smoothly, I will close the issue on GitHub.

**Comment by RuoCJ** [comment]
Pay attention to the grade column; it should correspond to the grade column in the data file. Only write from the start to the end.
If there are only two time periods, the difference in the grade column must be equal to 1.
